require: rubocop-rails

AllCops:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'test/test_helper.rb'
    - 'config/environments/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enable: false
